###Questionnaire 3 FONDNESS AND ADMIRATION###
module FondnessAndAdmiration

  #Questionnaire#

  fondness_and_admiration = Questionnaire.create!(title: "Fondness and Admiration", cutoff_score: 4, ok_score: 5, weight: 0.2) #cutoff_score < 4 and it's a bad thing

  #Grouping#

  fondness_turning_emotion_grouping = Grouping.create!(name: "Last Section")
  fondness_turning_emotion_grouping.questionnaires << fondness_and_admiration

  #Questions#

  fondness_and_admiration.questions.create! content: "My partner really respects me"
  fondness_and_admiration.questions.create! content: "I feel loved and cared for in this relationship"
  fondness_and_admiration.questions.create! content: "Romance is something our relationship definitely still has in it"
  fondness_and_admiration.questions.create! content: "When I come into a room my partner is glad to see me"
  fondness_and_admiration.questions.create! content: "My partner appreciates the things I do in this relationship"

  #PossibleResponses#

  true_false_normal = []
  (6..7).to_a.each {|num| true_false_normal << PossibleResponse.find(num)}

  fondness_and_admiration.questions.each do |question|
    true_false_normal.each do |response|
      question.possible_responses << response
    end
  end

  #Products#

  fondness_and_admiration_products = []

  fondness_and_admiration_products << Product.create!(name: "The Fondness & Admiration Checklist", data: {url: "http://www.behavioralsciencesofalabama.com/images/Fondness%20and%20Admiration.pdf"} , description: "It is very important to examine the positive aspects of your partner's personality. Many times when people are upset with one another they lose sight of all these positive aspects of the partner and of the relationship. If these positive areas of a partner or of the relationship get acknowledged and discussed, change is often more possible and exploring these areas that you appreciate may have positive consequences. Our fondness and admiration checklist helps you do just that.")
  fondness_and_admiration_products << Product.create!(name: "Personalized Therapy Help", data: {url: "https://www.gottmanreferralnetwork.com/"} , description: "A therapist! The very name makes you want cringe and reaffirm that your relationship is actually pretty good and that while maybe other couples might need professional help, you do not. Wrong. It's completely normal for couples in committed relationships to have issues that they need to work on. A therapist is like a doctor for your relationship and it's time for your yearly physical. Find one now:")

  #Responses#

  fondness_and_admiration.results.create!(quadrant_type: "individual_good", overall: "good", content: "Congratulations, you have built a lasting friendship system in your relationship where you feel loved, respected, and appreciated!", recommendation: "From your answers it's clear that you feel respected, admired, and well loved by your partner. Most likely, you not only think loving and appreciative thoughts about them but also express those thoughts through words and affection. In doing so you are actively working to create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and you have it!") #You scored good - you have no problems in this area

  ok = fondness_and_admiration.results.create!(quadrant_type: "individual_ok", overall: "ok", content: "Don't panic, but we want you to do a better job of building a lasting friendship system in your relationship where you feel loved, respected, and appreciated.", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with your partner to develop these fondness and admiration systems. In the case that you are not there, the goal of such a systems is to get to a point where you not only think loving and appreciative thoughts about your partner but also express those thoughts through words and affection. In doing so you will create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system has he potential to cause larger problem down the road. In order to enhance your friendship we recommend the following resource:") #You scored ok - you have some problems
  ok.products << fondness_and_admiration_products[0]

  bad = fondness_and_admiration.results.create!(quadrant_type: "individual_bad", overall: "bad", content: "Don't panic, but we want you to do a better job of building a lasting friendship system in your relationship where you feel loved, respected, and appreciated.", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with your partner to develop these fondness and admiration systems. In the case that you are not there, the goal of such a systems is to get to a point where you not only think loving and appreciative thoughts about your partner but also express those thoughts through words and affection. In doing so you will create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system is not supporting you a healthy way. In order to enhance your fondness and admiration systems we recommend the following resources:") #You scored bad - you have problems
  fondness_and_admiration_products.each {|product| bad.products << product}

  fondness_and_admiration.results.create!(quadrant_type: "couple_good_good", overall: "good", content: "Congratulations, you have built a lasting friendship system in your relationship where both you and your partner feel loved, respected, and appreciated!", recommendation: "From both of your answers it's clear that you feel respected, admired, and well loved by one another. Most likely you not only think loving and appreciative thoughts about each other but you also express these thoughts through words and affection. In doing so you are actively working to create a 'culture of appreciation' in your relationship, one where neither person feels taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and you have it!") # You both scored good - this relationship no problems

  bad = fondness_and_admiration.results.create!(quadrant_type: "couple_good_bad", overall: "bad", content: "Your partner needs your help in building a lasting friendship system where they feel loved, respected, and appreciated.", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with your partner to develop this fondness and admiration system in order to help them feel good about your relationship. Based on your partner's responses, chances are that currently they lack a sense that you are proud of what they have accomplished. Moreover they might even feel taken for granted. This can cause it to be hard for them to think loving and appreciative thoughts about you, and to express these thoughts through words and affection. A poor fondness and admiration system for either person in the relationship can be a significant problem for both your friendship and overall relationship. That said what you need to do now is work with them to develop a strong fondness and admiration system  since your current system is not supporting them a healthy way. In order to enhance your fondness and admiration systems we recommend the following resources:") #You scored good your partner scored bad - your partner needs your help badly!
  fondness_and_admiration_products.each {|product| bad.products << product}

  ok = fondness_and_admiration.results.create!(quadrant_type: "couple_good_ok", overall: "ok", content: "Your partner needs your help in building a lasting friendship system where they feel loved, respected, and appreciated.", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a slightly better job of working with your partner to develop a fondness and admiration system that is more supportive of their needs. The goal of developing such a systems is to get to a point where both partners think loving and appreciative thoughts about one another and also express these thoughts through words and affection. In doing this you will create a 'culture of appreciation' in your relationship, one where neither person feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system has he potential to cause larger problem down the road. In order to help your partner out and enhance your friendship we recommend the following resource:") # You scored good your partner scored ok - your partner has some issues that they need your help with
  ok.products << fondness_and_admiration_products[0]

  bad = fondness_and_admiration.results.create!(quadrant_type: "couple_bad_good", overall: "bad", content: "Don't panic, but we want you to do a better job of building a lasting friendship system in your relationship where you feel loved, respected, and appreciated", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with your partner to develop these fondness and admiration systems. In the case that you are not there, the goal of such a systems is to get to a point where you not only think loving and appreciative thoughts about your partner but also express those thoughts through words and affection. In doing so you will create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system is not supporting you a healthy way. In order to enhance your fondness and admiration systems we recommend working with your partner by using the following resources:") # You scored bad your partner scored good - you have some things you need to work on and you need your partner's help
  fondness_and_admiration_products.each {|product| bad.products << product}

  bad = fondness_and_admiration.results.create!(quadrant_type: "couple_bad_bad", overall: "bad", content: "You both need to do a better job of building a lasting friendship system in your relationship where you feel loved, respected, and appreciated by one another", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with one another to develop these fondness and admiration systems. In the case that it is not there, the goal of such a systems is to get to a point where you both think loving and appreciative thoughts about one another and also express these thoughts through words and affection. In doing so you will create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system is not supporting either of you a healthy way. In order to enhance your fondness and admiration systems we recommend the following resources:") # You both scored bad - you both have problems and need to work on this area
  fondness_and_admiration_products.each {|product| bad.products << product}

  bad = fondness_and_admiration.results.create!(quadrant_type: "couple_bad_ok", overall: "bad", content: "You both need to do a better job of building a lasting friendship system in your relationship where you feel loved, respected, and appreciated by one another", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with one another to develop these fondness and admiration systems. In the case that it is not there, the goal of such a systems is to get to a point where you both think loving and appreciative thoughts about one another and also express these thoughts through words and affection. In doing so you will create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system is not supporting either of you a healthy way. In order to enhance your fondness and admiration systems we recommend the following resources:") # You scored bad and your partner scored ok - you have some issues you need to work on and so does your partner to a lesser degree
  fondness_and_admiration_products.each {|product| bad.products << product}

  ok = fondness_and_admiration.results.create!(quadrant_type: "couple_ok_good", overall: "ok", content: "We think you can do a better job of working with your partner in order to build a lasting friendship system in your relationship where both you and your partner feel loved, respected, and appreciated", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a slightly better job of working with your partner to develop a fondness and admiration system that is more supportive of your needs. The goal of developing such a systems is to get to a point where you both think loving and appreciative thoughts about one another and also express these thoughts through words and affection. In doing this you will create a 'culture of appreciation' in your relationship, one where neither person feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system, while not a bad one, has he potential to cause larger problem down the road. In order to enhance your friendship we recommend the following resource:") # You scored ok and your partner scored good - you have some minor issues that you need your partner's help with
  ok.products << fondness_and_admiration_products[0]

  bad = fondness_and_admiration.results.create!(quadrant_type: "couple_ok_bad", overall: "bad", content: "You both need to do a better job of building a lasting friendship system in your relationship where you feel loved, respected, and appreciated by one another", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with one another to develop these fondness and admiration systems. In the case that it is not there, the goal of such a systems is to get to a point where you both think loving and appreciative thoughts about one another and also express these thoughts through words and affection. In doing so you will create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system is not supporting either of you a healthy way. In order to enhance your fondness and admiration systems we recommend the following resources:") # You scored ok and your partner scored bad - you have some minor issues and your partner has some major ones
  fondness_and_admiration_products.each {|product| bad.products << product}

  ok = fondness_and_admiration.results.create!(quadrant_type: "couple_ok_ok", overall: "ok", content: "It's close, but we think you can both do a better job of building a lasting friendship system in your relationship where you and your partner feel loved, respected, and appreciated", recommendation: "In any committed relationship it's important to feel respected, admired, and well loved. We think you can do a better job of working with one another to develop these fondness and admiration systems. In the case that it is not there, the goal of such a systems is to get to a point where you both think loving and appreciative thoughts about one another and also express these thoughts through words and affection. In doing so you will create a 'culture of appreciation' in your relationship, one where you don't feel taken for granted and where you are both proud of what you have accomplished. High fondness and admiration in a relationship is one of the three essential components of a good friendship, and we are worried that your current system is not supporting either of you an optimal way. In order to enhance your fondness and admiration systems we recommend the following resources:") # Both Partners Scored Just Ok - there are some minor issues that need to be addressed
  ok.products << fondness_and_admiration_products[0]
end