###Last Questionnaire OVERALL SCORE### 
module Overall

#Note this is not an actual questionnaire, it is just a means of determining overall results by aggregating all other results together

  #Questionnaire#

  overall_state = Questionnaire.create!(title: "Overall Relationship Score", cutoff_score: 90, ok_score: 80)

  #Products#
  
  overall_state_products = []

  overall_state_products << Product.create!(name: "The Art And Science Of Love", description: "This product is designed to help your relationship overall")
  overall_state_products << Product.create!(name: "Find a therapist by you", description: "Personalized therapy to help you with your relationship overall")

  #Results#

  overall_state.results.create!(quadrant_type: "individual_good", overall: "g", content: "Congratulations, your relationship overall is happy and healthy!", recommendation: "While there might be one or two specific areas for improvement, chances are that the relationship overall is happy. This means that you have a solid foundation of knowledge about your partner and their inner world, and that you have developed a fondness and admiration system where you feel loved, respected, and appreciated by your partner.  Furthermore your friendship robust and you feel your partner does a good job of noticing and engaging with your bids for attention. Most importantly though, you are engaged in the relationship and have created a good balance between dependence and interdependence where you can rely on one another to be there when you need it most. Amidst growing divorce and breakup rates world wide it’s really reassuring to see a relationship as sound as yours. Congratulations, you have something special.")#You scored good - you have no problems in this area

  ok = overall_state.results.create!(quadrant_type: "individual_ok", overall: "o", content: "It’s almost there but your relationship overall could use a boost in one or more areas.", recommendation: "Based on your scores there are one or more areas in your relationship that could use improvement. While you didn’t score poorly, you didn’t score perfectly either and we are worried that the issues you are currently experiencing might become larger and more problematic over time if you do nothing to fix them now. In over 40 years of researching relationships we found that couples who have small issues wait an average of 7 years before they get the help they need. By this time the issues have become large ones and there is so much negativity and resentment in the relationship that it’s often hard to salvage and the couple ends up breaking up. Don’t be a part of the growing statistic of couples splitting up. We really want you to work on the things that are troubling you and have many easy to use resources that are proven to give results. We believe in you and are here to help, take a look at the following resources in order to restore your relationship back to its glory days:") # You scored ok - you have some problems
  ok.products << overall_state_products[0]

  bad = overall_state.results.create!(quadrant_type: "individual_bad", overall: "b", content: "We would like you to work on your relationship overall.", recommendation: "Based on your scores there are one or more areas in your relationship that could use improvement. It’s good that you know what you need to work on because we are worried that the issues you are currently experiencing might become even larger and more problematic over time if you do nothing to fix them now. In over 40 years of researching relationships we found that couples who have even small issues wait an average of 7 years before they get the help they need.  By this time the issues are much larger and more painful, but don’t worry there is hope. The important thing is to realize we have your back and can assist you in working through these issues together with your partner. The time to do this is now. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you get things back on track. Take a look at the resources:") # You scored bad - you have problems
  overall_state_products.each {|product| bad.products << product}

  overall_state.results.create!(quadrant_type: "couple_good_good", overall: "g", content: "Congratulations, both of you agree that your relationship overall is happy and healthy!", recommendation: "While there might be one or two specific areas for improvement, chances are that both of you agree that the relationship overall is a happy one. This means that you have a solid foundation of knowledge about each others’ inner world, and that you have developed a fondness and admiration system where you both feel loved, respected, and appreciated by one another. Furthermore your friendship robust and you each feel your partner does a good job of noticing and engaging with your bids for attention. Most importantly though, you are both engaged in the relationship and have created a good balance between dependence and interdependence where you can rely on one another to be there when you need it most. Amidst growing divorce and breakup rates world wide it’s really reassuring to see a relationship as sound as yours. Congratulations, you have something special.") # You both scored good - this relationship no problems

  bad = overall_state.results.create!(quadrant_type: "couple_good_bad", overall: "b", content: "We would like you to work on your relationship overall.", recommendation: "While your score indicates that you are pretty happy with your relationship, your partner does not feel quite as good and they need your help. Based on their scores it is clear that one or more areas of the relationship are, from their perspective, in need of work. Because relationships are a team sport your partner really needs your help in order to be happy and feel safe and respected. In over 40 years of researching relationships we found that couples who have even small issues wait an average of 7 years before they get the help they need! By this time the issues are much larger and more painful, but this can all be avoided by working with your partner now to help them feel better. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you get things back on track. Help your partner out and take a look at the following resources:") # You scored good your partner scored bad - your partner needs your help badly!
  overall_state_products.each {|product| bad.products << product}

  ok = overall_state.results.create!(quadrant_type: "couple_good_ok", overall: "o", content: "It’s almost there but your relationship overall could use a boost in one or more areas.", recommendation: "Your score indicates that you are pretty happy with your relationship and your partner is almost on your level but they need a little bit of help from you to get there. Because relationships are a team sport your partner needs your help in order to feel as you do about this relationship. In over 40 years of research we found that couples who have even small issues typically wait an average of 7 years before they get the help they need. By this time the issues are much larger and more painful, but this can all be avoided by working with your partner now to help them feel better. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you and your partner prevent any bigger issues down the road. Help your partner out and take a look at the following resources:") # You scored good your partner scored ok - your partner has some issues that they need your help with
  ok.products << overall_state_products[0]

  bad = overall_state.results.create!(quadrant_type: "couple_bad_good", overall: "b", content: "We would like you to work on your relationship overall.", recommendation: "Based on your scores there are one or more areas in your relationship that could use improvement. It’s good that you know what you need to work on because we are worried that the issues you are currently experiencing might become even larger and more problematic over time if you do nothing to fix them now. In over 40 years of researching relationships we found that couples who have even small issues wait an average of 7 years before they get the help they need.  By this time the issues are much larger and more painful, but don’t worry there is hope. The important thing is to realize we have your back and can assist you in working through these issues together with your partner. The time to do this is now. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you get things back on track. Take a look at the following resources for help:") # You scored bad your partner scored good - you have some things you need to work on and you need your partner's help
  overall_state_products.each {|product| bad.products << product}

  bad = overall_state.results.create!(quadrant_type: "couple_bad_bad", overall: "b", content: "We would like you to work on your relationship overall.", recommendation: "You already knew this but based on both of your scores there are one or more areas in your relationship that can use improvement. It’s good that you know what you need to work on because we are worried that the issues you are currently experiencing might become even larger and more problematic over time if you do nothing to fix them now. In over 40 years of researching relationships we found that couples who have even small issues wait an average of 7 years before they get the help they need.  By this time the issues are much larger and more painful, but don’t worry there is hope. The important thing is to realize we have your back and can assist you in working through these issues together with your partner. The time to do this is now. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you get things back on track. Take a look at the following resources for help:") # You both scored bad - you both have problems and need to work on this area
  overall_state_products.each {|product| bad.products << product}

  bad = overall_state.results.create!(quadrant_type: "couple_bad_ok", overall: "b", content: "We would like you to work on your relationship overall.", recommendation: "You already knew this but based on both of your scores there are one or more areas in your relationship that can use improvement. It’s good that you know what you need to work on because we are worried that the issues you are currently experiencing might become even larger and more problematic over time if you do nothing to fix them now. In over 40 years of researching relationships we found that couples who have even small issues wait an average of 7 years before they get the help they need.  By this time the issues are much larger and more painful, but don’t worry there is hope. The important thing is to realize we have your back and can assist you in working through these issues together with your partner. The time to do this is now. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you get things back on track. Take a look at the following resources for help:") # You scored bad and your partner scored ok - you have some issues you need to work on and so does your partner to a lesser degree
  overall_state_products.each {|product| bad.products << product}

  ok = overall_state.results.create!(quadrant_type: "couple_ok_good", overall: "o", content: "It’s almost there but your relationship overall could use a boost in one or more areas.", recommendation: "Your score indicates that you are pretty happy with your relationship but we think that you can do a little better. Because relationships are a team sport we want you to work with your partner on those areas in which you don’t feel rock solid in order to get you to a place where you feel good. In over 40 years of research we found that couples who have even small issues typically wait an average of 7 years before they get the help they need. By this time the issues are much larger and more painful, but this can all be avoided by working with your partner now to help them feel better. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you and your partner prevent any bigger issues down the road. Take a look at the following resources and see if they are right for you:") #You scored ok and your partner scored good - you have some minor issues that you need your partner's help with
  ok.products << overall_state_products[0]

  bad = overall_state.results.create!(quadrant_type: "couple_ok_bad", overall: "b", content: "We would like you to work on your relationship overall.", recommendation: "Based on your scores there are one or more areas in your relationship that could use improvement, both for you and your partner. It’s good that you know what you need to work on because we are worried that the issues you are currently experiencing might become even larger and more problematic over time if you do nothing to fix them now. In over 40 years of researching relationships we found that couples who have even small issues wait an average of 7 years before they get the help they need.  By this time the issues are much larger and more painful, but don’t worry there is hope. The important thing is to realize we have your back and can assist you in working through these issues together with your partner. The time to do this is now. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you get things back on track. Take a look at the following resources:") # You scored ok and your partner scored bad - you have some minor issues and your partner has some major ones
  overall_state_products.each {|product| bad.products << product}

  ok = overall_state.results.create!(quadrant_type: "couple_ok_ok", overall: "o", content: "It’s almost there but your relationship overall could use a boost in one or more areas.", recommendation: "Based on your scores, both for you and your partner have one or more area in your relationship that could use improvement. While they don’t seem to be major problems right now, it’s good that you know what you need to work on because we are worried that the issues you are currently experiencing might become even larger and more problematic over time. In over 40 years of researching relationships we found that couples who have even small issues wait an average of 7 years before they get the help they need.  By this time the issues are much larger and more painful, but this can all be avoided by working on them with your partner now. While taking the first step is always the hardest, we are here to help and have scientifically proven solutions that are going to help you and your partner prevent any bigger issues down the road. Take a look at the following resources and see if they are right for you:") # You both scored just ok - there are some minor issues that need to be addressed for both of you
  ok.products << overall_state_products[0]
end