universals: &universals
  total_questions: 45
  last_questionnaire_id: 5

development:
  <<: *universals
  twilio_account_sid: 'ACc803a2858e6d34343a7985e3bf1a1644'
  twilio_auth_token: '6145e3a35e8c40eee9903222042de609'

test:
  <<: *universals

staging:
  <<: *universals

production:
  <<: *universals