# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca515054372eeb3fd1d8cefe9448d12a267195e0dfdb610d141a7f703aefb3a9497dc7b6cba89a4ecf0a447833a68ca10eb5e1e9f9f903b22e2ddda08d1549a2

test:
  secret_key_base: 7f4b230092c72803aa1aa1d56feee7ec7874b698ff5c179d3587f1a753125ce02b7c8ba9e1643b7dcddad77660523926903b3689edfe665fe0fd87c280933100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
