Backbone.Marionette.Renderer.render = (template, data) -> 
  return throw new Error("Cannot find template") unless template?
  return template(data)

window.CP = new Backbone.Marionette.Application()

window.CP.Settings = {
  lastQuestionnaireNumber: 5,
  lastGroupingNumber: 3,
  couplesWorkshopId: 12,
  personalizedTherapyHelpId : 2,
  totalQuestionCount: 45
}

window.CP.States = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District Of Columbia",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming"
}

window.CP.Months = {
  "01": "01 - Jan",
  "02": "02 - Feb",
  "03": "03 - Mar",
  "04": "04 - Apr",
  "05": "05 - May",
  "06": "06 - Jun",
  "07": "07 - Jul",
  "08": "08 - Aug",
  "09": "09 - Sep",
  "010": "10 - Oct",
  "011": "11 - Nov",
  "012": "12 - Dec",
}

window.CP.Years = [
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024",
  "2025",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
]